openapi: 3.0.0
info:
  title: Task API
  description: API для решения задач
  version: 1.0.0
servers:
  - url: localhost:8080
paths:
  /tasks:
    post:
      summary: Решить задачу
      description: Принимает данные о задаче и решает ее
      requestBody:
        description: Данные о задаче
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                task_description:
                  type: string
                  description: Описание задачи
                task_schema:
                  type: string
                  description: Схема задачи
                actions:
                  type: array
                  items:
                    type: string
                  description: Список возможных действий
                max_count:
                  type: integer
                  description: Максимальное количество действий
      responses:
        '200':
          description: Задача решена
          content:
            application/json:
              schema:
                type: object
                properties:
                  commandList:
                    type: array
                    items:
                      type: string
        '400':
          description: Задача не решена, так как формат данных неверный
          content:
            application/json:
              schema:
                type: object
                properties:
                  commandList:
                    type: array
                    items:
                      type: string